### ISSUE TITLE
Question: Text struct clashes with SwiftUI's Text

### ISSUE THREAD

**Issue by theolampert** [automerge/automerge-swift-archived#23]
This isn't a major problem since I think there is an argument to be made that automerge related code and SwiftUI related code should rarely need be in the same file. However, I did run across the case while testing out the library that both of these will clash requiring an end-user to namespace a component like `SwiftUI.Text("Foo")`

Maybe it's more important to keep `Text` data type consistent with the other libraries? feel free to close this issue if so.

**Comment by lightsprint09** [comment]
Thanks again for bringing this up. It really helps me to see all these different scenarios.

I think name-spacing as you describe it, is intended. It is the way of handling conflicting type names in Swift. By using the module name as a prefix. So I close this for now. 

Feel free to reopen if you think there are better alternatives we should discuss.
