### ISSUE TITLE
Rebuild rust lib

### ISSUE THREAD

**Issue by zeeyang** [automerge/automerge-swift-archived#24]
I'm interested in trying out a few changes in rust backend and repackage it into automerge-swift. It appears running `cargo build --release` generates a single universal static lib. How would I go about generating `libautomerge.a` for simulator and catalyst? Thank you!

**Comment by lightsprint09** [comment]
Great for bringing this up.

At the moment I working on a build script which install all required components and builds all required architectures. But I will not be able to finish it until next year. 

In the meantime you could just use the resulting `libautomerge.a` and copy it into `AutomergeRSBackend.xcframework/macos-x86_64`. This would replace the current binary with a newer one. By doing so you can try out the changes in the rust backend. But be aware that this workaround only works on macOS x86_64.

**Comment by zeeyang** [comment]
👍 thanks!

**Comment by lightsprint09** [comment]
@zeeyang I pushed an initial repo to build & distribute  automerge-rs as xcframework. Have look [here](https://github.com/lightsprint09/automerge-swift-backend)
