### ISSUE TITLE
Release mode crash: Can't unsafeBitCast between types of different sizes

### ISSUE THREAD

**Issue by endeavour42** [automerge/automerge-swift-archived#30]
only tried this on the "support-latest-rust-version" branch, might or might not apply to the "main" branch:

the tests are crashing with "Swift runtime failure: Can't unsafeBitCast between types of different sizes" on this line:

let typePtr = unsafeBitCast(Root.self, to: UnsafeMutableRawPointer.self)
KeyPathIntrospection.swift line 19

this is only happening in release mode (-O or -Osize). this doesn't happen in debug mode (-Onone)

<img width="1552" alt="Screenshot 2021-04-29 at 10 10 03" src="https://user-images.githubusercontent.com/469189/116530834-61127780-a8d6-11eb-915d-091cd0ba7450.png">

**Comment by lightsprint09** [comment]
Can you please provide more info about Versions of macOS & Swift you are using

**Comment by endeavour42** [comment]
it is on intel mac. i tested that on catalina + Xcode 12.4. since then i updated to big sur and Xcode 12.5, but haven't had a chance testing it on that setup. and the swift version - whatever comes with Xcode (shown as "swift 5" in Xcode, though it's probably some 5.x if to dig further).

**Comment by lightsprint09** [comment]
I try to reproduce this. Build my iOS  application in release mode and it did noch crash

**Comment by endeavour42** [comment]
interesting. try macOS app (that's where it was crashing for me)

**Comment by lightsprint09** [comment]
I can execute the performance  test in release mode without crashing. Will close this for now. Reopen if you encounter the crash again.
